// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABeMkQtUyCHYa2buFHN1BCpte0NewNkBc',
    appId: '1:832526824375:web:823a6fd97629cefcb62e32',
    messagingSenderId: '832526824375',
    projectId: 'social-app-7ee16',
    authDomain: 'social-app-7ee16.firebaseapp.com',
    storageBucket: 'social-app-7ee16.appspot.com',
    measurementId: 'G-5HBNF08QWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6-w9kAXPRCgxQuX66XratlEfle0aiHG4',
    appId: '1:832526824375:android:b4e25550e36b0a6ab62e32',
    messagingSenderId: '832526824375',
    projectId: 'social-app-7ee16',
    storageBucket: 'social-app-7ee16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf3j5bOov_UWNOq2vjsrOsA2Yn18f50Ho',
    appId: '1:832526824375:ios:5fb468a6d3f6b42ab62e32',
    messagingSenderId: '832526824375',
    projectId: 'social-app-7ee16',
    storageBucket: 'social-app-7ee16.appspot.com',
    iosClientId: '832526824375-lch37hjcu7ssjbt2l842193ivhucc3rv.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf3j5bOov_UWNOq2vjsrOsA2Yn18f50Ho',
    appId: '1:832526824375:ios:5fb468a6d3f6b42ab62e32',
    messagingSenderId: '832526824375',
    projectId: 'social-app-7ee16',
    storageBucket: 'social-app-7ee16.appspot.com',
    iosClientId: '832526824375-lch37hjcu7ssjbt2l842193ivhucc3rv.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialapp',
  );
}
